name: Test

on:
  push:
    branches: [ master, patch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        package-manager: ['npm@latest-2', 'npm@latest-3', 'npm@latest-4', 'npm@latest-5', 'npm@latest-6', 'yarn', 'pnpm@latest-3', 'pnpm@latest-4', 'pnpm']
        node-version: [10]
        include:
          - package-manager: 'yarn@latest'
            node-version: 10
            berry: true
          - package-manager: 'npm@latest-1'
            node-version: 6
          - package-manager: 'npm@next-7'
            node-version: 14
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install package manager
      run: |
        pm=${{ matrix.package-manager }}
        npm install -g $pm
        echo "::set-env name=PM::${pm%@*}"
    - name: Install Yarn 2
      run: yarn set version berry
      if: matrix.berry
    - name: Install dependencies
      run: $PM install
    - run: $PM test

    - name: Install debug
      run: $PM add debug || $PM install debug
    - run: DEBUG=* $PM test
      
